New/Solution/App/Areas/Admin/Controllers/ArticleTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NkjSoft.DAL.Business;
using NkjSoft.Framework.Data;
using Models;

using NkjSoft.Framework;
using System.ComponentModel.Composition;
using NkjSoft.Framework.Extensions;

namespace NkjSoft.App.Areas.Admin.Controllers
{
    [Export]
    public class ArticleTypeController : BaseController
    {
        [Import]
        private NkjSoft.DAL.Business.Repository.IArticleTypeRepository ArticleTypeService { get; set; }

        //
        // GET: /Admin/ArticleType/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetArticleTypeListJson()
        {
            var result = ArticleTypeService.Entities.Select(p => new
            {
                Name = p.Name,
                Description = p.Description,
                Id = p.Id,
                TypeValue = p.TypeValue,
                AddDate = p.AddDate,
            })
            .ToList().AsPagedList(ArticleTypeService.Entities.Count());

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Admin/ArticleType/Details/5

        public ActionResult Details(Nullable<Guid> id = null)
        {
            ArticleType articletype = ArticleTypeService.GetByKey(id.GetValueOrDefault());
            if (articletype == null)
            {
                return HttpNotFound();
            }
            return View(articletype);
        }

        //
        // GET: /Admin/ArticleType/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Admin/ArticleType/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleType articletype)
        {
            if (ModelState.IsValid)
            {
                articletype.Id = Guid.NewGuid();
                ArticleTypeService.Insert(articletype);
                return RedirectToAction("Index");
            }

            return View(articletype);
        }

        //
        // GET: /Admin/ArticleType/Edit/5

        public ActionResult Edit(Nullable<Guid> id = null)
        {
            ArticleType articletype = ArticleTypeService.GetByKey(id.GetValueOrDefault());
            if (articletype == null)
            {
                return HttpNotFound();
            }
            return View(articletype);
        }

        //
        // POST: /Admin/ArticleType/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleType articletype)
        {
            if (ModelState.IsValid)
            {
                ArticleTypeService.Update(articletype);
                return RedirectToAction("Index");
            }
            return View(articletype);
        }

        //
        // GET: /Admin/ArticleType/Delete/5

        public ActionResult Delete(Nullable<Guid> id = null)
        {
            ArticleType articletype = GetArticleTypeInstance(id);
            if (articletype == null)
            {
                return HttpNotFound();
            }
            return View(articletype);
        }

        private ArticleType GetArticleTypeInstance(Nullable<Guid> id)
        {
            ArticleType articletype = ArticleTypeService.GetByKey(id.GetValueOrDefault());
            return articletype;
        }

        //
        // POST: /Admin/ArticleType/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ArticleType articletype = GetArticleTypeInstance(id);
            ArticleTypeService.Delete(articletype);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

New/Solution/App/Areas/Admin/Views/ArticleType/Create.cshtml
@model NkjSoft.DAL.Business.ArticleType

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.Backend.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ArticleType</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TypeValue)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TypeValue)
            @Html.ValidationMessageFor(model => model.TypeValue)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AddDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AddDate)
            @Html.ValidationMessageFor(model => model.AddDate)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

New/Solution/App/Areas/Admin/Views/ArticleType/Delete.cshtml
@model NkjSoft.DAL.Business.ArticleType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.Backend.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ArticleType</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TypeValue)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TypeValue)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.__KeyId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.__KeyId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AddDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AddDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

New/Solution/App/Areas/Admin/Views/ArticleType/Details.cshtml
@model NkjSoft.DAL.Business.ArticleType

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.Backend.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>ArticleType</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TypeValue)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TypeValue)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.__KeyId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.__KeyId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AddDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AddDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

New/Solution/App/Areas/Admin/Views/ArticleType/Edit.cshtml
@model NkjSoft.DAL.Business.ArticleType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.Backend.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ArticleType</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TypeValue)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TypeValue)
            @Html.ValidationMessageFor(model => model.TypeValue)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.AddDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AddDate)
            @Html.ValidationMessageFor(model => model.AddDate)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

New/Solution/App/Areas/Admin/Views/ArticleType/Index.cshtml
@model NkjSoft.DAL.Business.ArticleType

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layout.Index.cshtml";
}

@section TitleContent{
    <h1>类型列表</h1>
    }

<div class="search-panel" style="margin-bottom: 10px">
    <div id="divQuery" class="control-list">
        <div class="input_search">
            @Html.LabelFor(p=>p.Name)
            <input type='text' id='Name' />
        </div>
        <a href="javascript:void(0);"  class="l-btn search-button easyui-linkbutton easyui-linkbutton-blue" data-options="">查 询</a>
    </div>
</div>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
 *@

<table id="datagrid" 
        singleSelect="false" title="" url="@Url.Action("GetArticleTypeListJson", "ArticleType")" >
</table>

<script type="text/javascript">

    function _initGrid() {
        initialDataGrid([[
            { field: 'Name', title: '@Html.DisplayNameFor(model => model.Name)', width: 200 },
           { field: 'Description', title: '@Html.DisplayNameFor(model => model.Description)', width: 200 },
           { field: 'AddDate', title: '@Html.DisplayNameFor(model => model.AddDate)', width: 300 }
        ]], { multipleSelect: true });
    }

    $(function () {


        $(".removeBtn").live("click", function (e) {
            alert("ads");
        });
    });

    function buildParams(param) {
        buildUpParams(param);
    }

    function _DoSearch2() {
        $.ajax({
            type: "POST",
            url: "@Url.Action("GetArticleTypeListJson", "ArticleType")",
            data: {
                page: 1,
                rows: 5
            },
            dataType: "json",
            traditional: true,
            success: function (e) {
                alert($.toJSON(e));
            },
            error: function (e) {
                alert($.toJSON(e));
            }
        });
    }

    function flexiQuery() {
    }

</script>